packages:
  - packages/*
  - demo/*
  - cypress/fixtures/*
  - docs
patchedDependencies:
  '@hedgedoc/markdown-it-plugins@2.1.4': patches/@hedgedoc__markdown-it-plugins@2.1.4.patch
  markdown-it-mdc@0.2.5: patches/markdown-it-mdc.patch
catalog:
  '@antfu/eslint-config': ^4.8.1
  '@antfu/ni': ^24.1.0
  '@antfu/utils': ^9.1.0
  '@hedgedoc/markdown-it-plugins': ^2.1.4
  '@iconify-json/carbon': ^1.2.8
  '@iconify-json/mdi': ^1.2.3
  '@iconify-json/ph': ^1.2.2
  '@iconify-json/ri': ^1.2.5
  '@iconify-json/svg-spinners': ^1.2.2
  '@iconify/json': ^2.2.315
  '@lillallol/outline-pdf': ^4.0.0
  '@shikijs/engine-javascript': ^3.1.0
  '@shikijs/markdown-it': ^3.1.0
  '@shikijs/monaco': ^3.1.0
  '@shikijs/twoslash': ^3.1.0
  '@shikijs/vitepress-twoslash': ^3.1.0
  '@slidev/cli': ^51.3.0
  '@slidev/rough-notation': ^0.1.0
  '@slidev/theme-default': latest
  '@slidev/theme-seriph': latest
  '@slidev/types': ^51.3.0
  '@types/cli-progress': ^3.11.6
  '@types/connect': ^3.4.38
  '@types/debug': ^4.1.12
  '@types/file-saver': ^2.0.7
  '@types/js-yaml': ^4.0.9
  '@types/katex': ^0.16.7
  '@types/markdown-it': ^14.1.2
  '@types/picomatch': ^3.0.2
  '@types/node': ^22.13.10
  '@types/plantuml-encoder': ^1.4.2
  '@types/prompts': ^2.4.9
  '@types/recordrtc': ^5.6.14
  '@types/resolve': ^1.20.6
  '@types/semver': ^7.5.8
  '@types/vscode': ^1.89.0
  '@types/yargs': ^17.0.33
  '@types/markdown-it-emoji': ^3.0.1
  '@typescript/ata': ^0.9.7
  '@unhead/vue': ^1.11.20
  '@unocss/extractor-mdc': ^66.0.0
  '@unocss/reset': ^66.0.0
  '@vitejs/plugin-vue': ^5.2.1
  '@vitejs/plugin-vue-jsx': ^4.1.1
  '@volar/language-server': ~2.4.12
  '@volar/vscode': ^2.4.12
  '@vue/compiler-sfc': ^3.5.13
  '@vueuse/core': ^13.0.0
  '@vueuse/math': ^13.0.0
  '@vueuse/motion': ^3.0.1
  bumpp: ^10.0.3
  chokidar: ^4.0.3
  cli-progress: ^3.12.0
  connect: ^3.7.0
  cross-env: ^7.0.3
  cypress: ^13.17.0
  debug: ^4.4.0
  drauu: ^0.4.3
  eslint: ^9.22.0
  eslint-plugin-format: ^1.0.1
  esno: ^4.8.0
  fast-deep-equal: ^3.1.3
  fast-glob: ^3.3.3
  file-saver: ^2.0.5
  floating-vue: ^5.2.2
  fuse.js: ^7.1.0
  get-port-please: ^3.1.2
  global-directory: ^4.0.1
  gray-matter: ^4.0.3
  htmlparser2: ^10.0.0
  is-installed-globally: ^1.0.0
  jiti: ^2.4.2
  katex: ^0.16.21
  ansis: ^3.17.0
  lint-staged: ^15.4.3
  local-pkg: ^1.1.1
  lz-string: ^1.5.0
  magic-string: ^0.30.17
  magic-string-stack: ^1.0.0
  markdown-it: ^14.1.0
  markdown-it-footnote: ^4.0.0
  markdown-it-mdc: ^0.2.5
  markdown-it-emoji: ^3.0.0
  mermaid: ^11.4.1
  picomatch: ^4.0.2
  minimist: ^1.2.8
  mlly: ^1.7.4
  monaco-editor: 0.51.0
  nanotar: ^0.2.0
  nodemon: ^3.1.9
  open: ^10.1.0
  ovsx: ^0.10.1
  pdf-lib: ^1.17.1
  plantuml-encoder: ^1.4.0
  playwright-chromium: ^1.51.0
  postcss-nested: ^7.0.2
  pptxgenjs: ^3.12.0
  prettier: ^3.5.3
  prettier-plugin-slidev: ^1.0.5
  prompts: ^2.4.2
  public-ip: ^7.0.1
  reactive-vscode: ^0.2.13
  recordrtc: ^5.6.2
  resolve-from: ^5.0.0
  resolve-global: ^2.0.0
  rimraf: ^6.0.1
  semver: ^7.7.1
  shiki: ^3.1.0
  shiki-magic-move: ^1.0.1
  simple-git-hooks: ^2.11.1
  sirv: ^3.0.1
  source-map-js: ^1.2.1
  taze: ^19.0.1
  tinyexec: ^0.3.2
  tm-grammars: ^1.22.19
  ts-json-schema-generator: ^2.3.0
  tsup: ^8.4.0
  typeit: 8.1.0
  typescript: ^5.8.2
  unocss: ^66.0.0
  unplugin-icons: ^22.1.0
  unplugin-vue-components: ^28.4.1
  unplugin-vue-markdown: ^28.3.1
  untun: ^0.1.3
  uqr: ^0.1.2
  vite: ^6.2.1
  vite-plugin-inspect: ^11.0.0
  vite-plugin-remote-assets: ^1.0.0
  vite-plugin-static-copy: ^2.3.0
  vite-plugin-vue-server-ref: ^1.0.0
  vitefu: ^1.0.6
  vitepress: ^2.0.0-alpha.4
  vitest: ^3.0.8
  volar-service-prettier: ^0.0.63
  volar-service-yaml: ^0.0.63
  vue: ^3.5.13
  vue-router: ^4.5.0
  vue-tsc: ^2.2.8
  yaml: ^2.7.0
  yargs: ^17.7.2
  zx: ^8.4.0
onlyBuiltDependencies:
  - cypress
  - esbuild
  - playwright-chromium
