catalogMode: prefer
ignoreWorkspaceRootCheck: true
shamefullyHoist: true
shellEmulator: true
trustPolicy: no-downgrade

packages:
  - packages/*
  - demo/*
  - cypress/fixtures/*
  - docs

strictPeerDependencies: false
linkWorkspacePackages: true

patchedDependencies:
  '@hedgedoc/markdown-it-plugins@2.1.4': patches/@hedgedoc__markdown-it-plugins@2.1.4.patch
catalogs:
  demo:
    '@vue/compiler-sfc': ^3.5.25
  dev:
    '@antfu/eslint-config': ^6.5.1
    bumpp: ^10.3.2
    cypress: ^14.5.4
    eslint: ^9.39.1
    eslint-plugin-format: ^1.1.0
    lint-staged: ^16.2.7
    nodemon: ^3.1.11
    ovsx: ^0.10.7
    playwright-chromium: ^1.57.0
    postcss-nested: ^7.0.2
    prettier: ^3.7.4
    prettier-plugin-slidev: ^1.0.5
    rimraf: ^6.1.2
    simple-git-hooks: ^2.13.1
    taze: ^19.9.2
    tsdown: ^0.17.2
    tsx: ^4.21.0
    typescript: ^5.9.3
    vitefu: ^1.1.1
    vitest: ^4.0.15
    vue-tsc: ^3.1.8
    zx: ^8.8.5
  docs:
    typeit: 8.1.0
    vitepress: ^2.0.0-alpha.15
    vitepress-plugin-group-icons: ^1.6.5
    vitepress-plugin-llms: ^1.9.3
  frontend:
    '@antfu/utils': ^9.3.0
    '@shikijs/engine-javascript': ^3.19.0
    '@shikijs/markdown-it': ^3.19.0
    '@slidev/rough-notation': ^0.1.0
    '@unhead/vue': ^2.0.19
    '@unocss/reset': ^66.5.10
    '@vueuse/core': ^14.1.0
    '@vueuse/math': ^14.1.0
    '@vueuse/motion': ^3.0.3
    drauu: ^0.4.3
    file-saver: ^2.0.5
    floating-vue: ^5.2.2
    fuse.js: ^7.1.0
    katex: ^0.16.27
    lz-string: ^1.5.0
    mermaid: ^11.12.2
    nanotar: ^0.2.0
    plantuml-encoder: ^1.4.0
    recordrtc: ^5.6.2
    shiki: ^3.19.0
    shiki-magic-move: ^1.2.1
    tm-grammars: ^1.26.0
    unhead: ^2.0.19
    vue: ^3.5.25
    vue-router: ^4.6.3
  icons:
    '@iconify-json/carbon': ^1.2.15
    '@iconify-json/mdi': ^1.2.3
    '@iconify-json/ph': ^1.2.2
    '@iconify-json/ri': ^1.2.6
    '@iconify-json/svg-spinners': ^1.2.4
    '@iconify/json': ^2.2.416
  monaco:
    '@shikijs/monaco': ^3.19.0
    '@typescript/ata': ^0.9.8
    monaco-editor: ^0.55.1
  prod:
    '@antfu/ni': ^28.0.0
    '@hedgedoc/markdown-it-plugins': ^2.1.4
    '@lillallol/outline-pdf': ^4.0.0
    '@shikijs/twoslash': ^3.19.0
    '@shikijs/vitepress-twoslash': ^3.19.0
    '@unocss/extractor-mdc': ^66.5.10
    '@vitejs/plugin-vue': ^6.0.2
    '@vitejs/plugin-vue-jsx': ^5.1.2
    ansis: ^4.2.0
    chokidar: ^4.0.3
    cli-progress: ^3.12.0
    connect: ^3.7.0
    fast-deep-equal: ^3.1.3
    fast-glob: ^3.3.3
    get-port-please: ^3.2.0
    global-directory: ^4.0.1
    gray-matter: ^4.0.3
    htmlparser2: ^10.0.0
    is-installed-globally: ^1.0.0
    jiti: ^2.6.1
    local-pkg: ^1.1.2
    magic-string: ^0.30.21
    magic-string-stack: ^1.1.0
    markdown-it: ^14.1.0
    markdown-it-footnote: ^4.0.0
    markdown-it-mdc: ^0.2.6
    minimist: ^1.2.8
    mlly: ^1.8.0
    obug: ^2.1.1
    open: ^11.0.0
    pdf-lib: ^1.17.1
    picomatch: ^4.0.3
    pptxgenjs: ^4.0.1
    prompts: ^2.4.2
    public-ip: ^8.0.0
    resolve-from: ^5.0.0
    resolve-global: ^2.0.0
    semver: ^7.7.3
    sirv: ^3.0.2
    source-map-js: ^1.2.1
    tinyexec: ^1.0.2
    unocss: ^66.5.10
    unplugin-icons: ^22.5.0
    unplugin-vue-components: ^30.0.0
    unplugin-vue-markdown: ^29.2.0
    untun: ^0.1.3
    uqr: ^0.1.2
    vite: ^7.2.7
    vite-plugin-inspect: ^11.3.3
    vite-plugin-remote-assets: ^2.1.0
    vite-plugin-static-copy: ^3.1.4
    vite-plugin-vue-server-ref: ^1.0.0
    yaml: ^2.8.2
    yargs: ^18.0.0
  themes:
    '@slidev/theme-default': ^0.25.0
    '@slidev/theme-seriph': ^0.25.0
  types:
    '@types/cli-progress': ^3.11.6
    '@types/connect': ^3.4.38
    '@types/file-saver': ^2.0.7
    '@types/js-yaml': ^4.0.9
    '@types/katex': ^0.16.7
    '@types/markdown-it': ^14.1.2
    '@types/node': ^24.10.2
    '@types/picomatch': ^4.0.2
    '@types/plantuml-encoder': ^1.4.2
    '@types/prompts': ^2.4.9
    '@types/recordrtc': ^5.6.15
    '@types/resolve': ^1.20.6
    '@types/semver': ^7.7.1
    '@types/yargs': ^17.0.35
  vscode:
    '@volar/language-server': ~2.4.26
    '@volar/vscode': ^2.4.26
    picomatch: ^4.0.3
    prettier: ^2.8.8
    reactive-vscode: ^0.4.1
    ts-json-schema-generator: ^2.4.0
    volar-service-prettier: ^0.0.64
    volar-service-yaml: ^0.0.64
    yaml-language-server: ^1.19.2
onlyBuiltDependencies:
  - '@vscode/vsce-sign'
  - cypress
  - esbuild
  - keytar
  - playwright-chromium
  - simple-git-hooks
  - typeit
  - unrs-resolver
