packages:
  - packages/*
  - demo/*
  - cypress/fixtures/*
  - docs

patchedDependencies:
  '@hedgedoc/markdown-it-plugins@2.1.4': patches/@hedgedoc__markdown-it-plugins@2.1.4.patch

catalogs:
  demo:
    '@vue/compiler-sfc': ^3.5.13
  dev:
    '@antfu/eslint-config': ^4.12.0
    bumpp: ^10.1.0
    cross-env: ^7.0.3
    cypress: ^13.17.0
    eslint: ^9.25.1
    eslint-plugin-format: ^1.0.1
    lint-staged: ^15.5.1
    nodemon: ^3.1.9
    ovsx: ^0.10.2
    playwright-chromium: ^1.52.0
    postcss-nested: ^7.0.2
    prettier: ^3.5.3
    prettier-plugin-slidev: ^1.0.5
    rimraf: ^6.0.1
    simple-git-hooks: ^2.12.1
    taze: ^19.0.4
    tsup: ^8.4.0
    tsx: ^4.19.3
    typescript: ^5.8.3
    vitefu: ^1.0.6
    vitest: ^3.1.2
    vue-tsc: ^2.2.8
    zx: ^8.5.3
  docs:
    typeit: 8.1.0
    vitepress: ^2.0.0-alpha.5
    vitepress-plugin-group-icons: ^1.5.5
    vitepress-plugin-llms: ^1.1.0
  frontend:
    '@antfu/utils': ^9.2.0
    '@shikijs/engine-javascript': ^3.3.0
    '@shikijs/markdown-it': ^3.3.0
    '@slidev/rough-notation': ^0.1.0
    '@unhead/vue': ^2.0.8
    '@unocss/reset': ^66.0.0
    '@vueuse/core': ^13.1.0
    '@vueuse/math': ^13.1.0
    '@vueuse/motion': ^3.0.3
    drauu: ^0.4.3
    file-saver: ^2.0.5
    floating-vue: ^5.2.2
    fuse.js: ^7.1.0
    katex: ^0.16.22
    lz-string: ^1.5.0
    mermaid: ^11.6.0
    nanotar: ^0.2.0
    plantuml-encoder: ^1.4.0
    recordrtc: ^5.6.2
    shiki: ^3.3.0
    shiki-magic-move: ^1.1.0
    tm-grammars: ^1.23.15
    unhead: ^2.0.8
    vue: ^3.5.13
    vue-router: ^4.5.0
  icons:
    '@iconify-json/carbon': ^1.2.8
    '@iconify-json/mdi': ^1.2.3
    '@iconify-json/ph': ^1.2.2
    '@iconify-json/ri': ^1.2.5
    '@iconify-json/svg-spinners': ^1.2.2
    '@iconify/json': ^2.2.330
  monaco:
    '@shikijs/monaco': ^3.3.0
    '@typescript/ata': ^0.9.7
    monaco-editor: 0.51.0
  prod:
    '@antfu/ni': ^24.3.0
    '@hedgedoc/markdown-it-plugins': ^2.1.4
    '@lillallol/outline-pdf': ^4.0.0
    '@shikijs/twoslash': ^3.3.0
    '@shikijs/vitepress-twoslash': ^3.3.0
    '@unocss/extractor-mdc': ^66.0.0
    '@vitejs/plugin-vue': ^5.2.3
    '@vitejs/plugin-vue-jsx': ^4.1.2
    ansis: ^3.17.0
    chokidar: ^4.0.3
    cli-progress: ^3.12.0
    connect: ^3.7.0
    debug: ^4.4.0
    fast-deep-equal: ^3.1.3
    fast-glob: ^3.3.3
    get-port-please: ^3.1.2
    global-directory: ^4.0.1
    gray-matter: ^4.0.3
    htmlparser2: ^10.0.0
    is-installed-globally: ^1.0.0
    jiti: ^2.4.2
    local-pkg: ^1.1.1
    magic-string: ^0.30.17
    magic-string-stack: ^1.0.0
    markdown-it: ^14.1.0
    markdown-it-footnote: ^4.0.0
    markdown-it-mdc: ^0.2.5
    minimist: ^1.2.8
    mlly: ^1.7.4
    open: ^10.1.1
    pdf-lib: ^1.17.1
    picomatch: ^4.0.2
    pptxgenjs: ^3.12.0
    prompts: ^2.4.2
    public-ip: ^7.0.1
    resolve-from: ^5.0.0
    resolve-global: ^2.0.0
    semver: ^7.7.1
    sirv: ^3.0.1
    source-map-js: ^1.2.1
    tinyexec: ^1.0.1
    unocss: ^66.0.0
    unplugin-icons: ^22.1.0
    unplugin-vue-components: ^28.5.0
    unplugin-vue-markdown: ^28.3.1
    untun: ^0.1.3
    uqr: ^0.1.2
    vite: ^6.3.2
    vite-plugin-inspect: ^11.0.1
    vite-plugin-remote-assets: ^2.0.0
    vite-plugin-static-copy: ^2.3.1
    vite-plugin-vue-server-ref: ^1.0.0
    yaml: ^2.7.1
    yargs: ^17.7.2
  themes:
    '@slidev/theme-default': ^0.25.0
    '@slidev/theme-seriph': ^0.25.0
  types:
    '@types/cli-progress': ^3.11.6
    '@types/connect': ^3.4.38
    '@types/debug': ^4.1.12
    '@types/file-saver': ^2.0.7
    '@types/js-yaml': ^4.0.9
    '@types/katex': ^0.16.7
    '@types/markdown-it': ^14.1.2
    '@types/node': ^22.14.1
    '@types/picomatch': ^4.0.0
    '@types/plantuml-encoder': ^1.4.2
    '@types/prompts': ^2.4.9
    '@types/recordrtc': ^5.6.14
    '@types/resolve': ^1.20.6
    '@types/semver': ^7.7.0
    '@types/vscode': ^1.89.0
    '@types/yargs': ^17.0.33
  vscode:
    '@volar/language-server': ~2.4.12
    '@volar/vscode': ^2.4.12
    reactive-vscode: ^0.2.14
    ts-json-schema-generator: ^2.4.0
    volar-service-prettier: ^0.0.64
    volar-service-yaml: ^0.0.64

onlyBuiltDependencies:
  - cypress
  - esbuild
  - playwright-chromium
  - unrs-resolver
