packages:
  - packages/*
  - demo/*
  - cypress/fixtures/*
  - docs
catalog:
  '@antfu/eslint-config': ^2.27.2
  '@antfu/ni': ^0.22.4
  '@antfu/utils': ^0.7.10
  '@hedgedoc/markdown-it-plugins': ^2.1.4
  '@iconify-json/carbon': ^1.1.37
  '@iconify-json/mdi': ^1.1.68
  '@iconify-json/ph': ^1.1.14
  '@iconify-json/ri': ^1.1.22
  '@iconify-json/svg-spinners': ^1.1.3
  '@iconify/json': ^2.2.241
  '@lillallol/outline-pdf': ^4.0.0
  '@shikijs/markdown-it': ^1.14.1
  '@shikijs/monaco': ^1.14.1
  '@shikijs/twoslash': ^1.14.1
  '@shikijs/vitepress-twoslash': ^1.14.1
  '@slidev/rough-notation': ^0.1.0
  '@slidev/theme-default': ^0.25.0
  '@slidev/theme-seriph': ^0.25.0
  '@types/cli-progress': ^3.11.6
  '@types/connect': ^3.4.38
  '@types/debug': ^4.1.12
  '@types/file-saver': ^2.0.7
  '@types/fs-extra': ^11.0.4
  '@types/js-yaml': ^4.0.9
  '@types/katex': ^0.16.7
  '@types/markdown-it': ^14.1.2
  '@types/micromatch': ^4.0.9
  '@types/node': ^22.5.0
  '@types/plantuml-encoder': ^1.4.2
  '@types/prismjs': ^1.26.4
  '@types/prompts': ^2.4.9
  '@types/recordrtc': ^5.6.14
  '@types/resolve': ^1.20.6
  '@types/semver': ^7.5.8
  '@types/yargs': ^17.0.33
  '@typescript/ata': ^0.9.7
  '@unhead/vue': ^1.10.0
  '@unocss/extractor-mdc': ^0.62.3
  '@unocss/reset': ^0.62.3
  '@vitejs/plugin-vue': ^5.1.2
  '@vitejs/plugin-vue-jsx': ^4.0.1
  '@volar/language-server': ~2.4.0
  '@volar/vscode': ^2.4.0
  '@vue/compiler-sfc': ^3.4.38
  '@vueuse/core': ^11.0.3
  '@vueuse/math': ^11.0.3
  '@vueuse/motion': ^2.2.3
  bumpp: ^9.5.2
  chokidar: ^3.6.0
  cli-progress: ^3.12.0
  connect: ^3.7.0
  cross-env: ^7.0.3
  cypress: ^13.13.3
  debug: ^4.3.6
  drauu: ^0.4.1
  eslint: ^9.9.1
  eslint-plugin-format: ^0.1.2
  esno: ^4.7.0
  execa: ^9.3.1
  fast-deep-equal: ^3.1.3
  fast-glob: ^3.3.2
  file-saver: ^2.0.5
  floating-vue: ^5.2.2
  fs-extra: ^11.2.0
  fuse.js: ^7.0.0
  get-port-please: ^3.1.2
  global-directory: ^4.0.1
  gray-matter: ^4.0.3
  htmlparser2: ^9.1.0
  is-installed-globally: ^1.0.0
  jiti: ^1.21.6
  katex: ^0.16.11
  kolorist: ^1.8.0
  lint-staged: ^15.2.9
  local-pkg: ^0.5.0
  lz-string: ^1.5.0
  magic-string: ^0.30.11
  magic-string-stack: ^0.1.1
  markdown-it: ^14.1.0
  markdown-it-footnote: ^4.0.0
  markdown-it-mdc: ^0.2.5
  mermaid: ^11.0.2
  micromatch: ^4.0.8
  minimist: ^1.2.8
  mlly: ^1.7.1
  monaco-editor: ^0.51.0
  nodemon: ^3.1.4
  open: ^10.1.0
  ovsx: ^0.9.2
  pdf-lib: ^1.17.1
  plantuml-encoder: ^1.4.0
  playwright-chromium: ^1.46.1
  postcss-nested: ^6.2.0
  pptxgenjs: ^3.12.0
  prettier: ^3.3.3
  prettier-plugin-slidev: ^1.0.5
  prismjs: ^1.29.0
  prompts: ^2.4.2
  public-ip: ^7.0.1
  reactive-vscode: 0.2.0
  recordrtc: ^5.6.2
  resolve-from: ^5.0.0
  resolve-global: ^2.0.0
  rimraf: ^6.0.1
  semver: ^7.6.3
  shiki: ^1.14.1
  shiki-magic-move: ^0.4.4
  simple-git-hooks: ^2.11.1
  sirv: ^2.0.4
  source-map-js: ^1.2.0
  taze: ^0.16.6
  tm-grammars: ^1.17.4
  ts-json-schema-generator: ^2.3.0
  tsup: ^8.2.4
  typeit: 8.1.0
  typescript: ^5.5.4
  unocss: ^0.62.3
  unplugin-icons: ^0.19.2
  unplugin-vue-components: ^0.27.4
  unplugin-vue-markdown: ^0.26.2
  untun: ^0.1.3
  uqr: ^0.1.2
  vite: ^5.4.2
  vite-plugin-inspect: ^0.8.7
  vite-plugin-remote-assets: ^0.5.0
  vite-plugin-static-copy: ^1.0.6
  vite-plugin-vue-server-ref: ^0.4.2
  vitefu: ^0.2.5
  vitepress: ^1.3.4
  vitest: ^2.0.5
  volar-service-prettier: ^0.0.61
  volar-service-yaml: ^0.0.61
  vue: ^3.4.38
  vue-router: ^4.4.3
  vue-tsc: ^2.0.29
  yaml: ^2.5.0
  yargs: ^17.7.2
  zx: ^8.1.4
