packages:
  - packages/*
  - demo/*
  - cypress/fixtures/*
  - docs
catalog:
  '@antfu/eslint-config': ^4.1.0
  '@antfu/ni': ^23.3.0
  '@antfu/utils': ^8.1.0
  '@hedgedoc/markdown-it-plugins': ^2.1.4
  '@iconify-json/carbon': ^1.2.5
  '@iconify-json/mdi': ^1.2.3
  '@iconify-json/ph': ^1.2.2
  '@iconify-json/ri': ^1.2.5
  '@iconify-json/svg-spinners': ^1.2.2
  '@iconify/json': ^2.2.300
  '@lillallol/outline-pdf': ^4.0.0
  '@shikijs/engine-javascript': ^2.1.0
  '@shikijs/markdown-it': ^2.1.0
  '@shikijs/monaco': ^2.1.0
  '@shikijs/twoslash': ^2.1.0
  '@shikijs/vitepress-twoslash': ^2.1.0
  '@slidev/rough-notation': ^0.1.0
  '@slidev/theme-default': ^0.25.0
  '@slidev/theme-seriph': ^0.25.0
  '@types/cli-progress': ^3.11.6
  '@types/connect': ^3.4.38
  '@types/debug': ^4.1.12
  '@types/file-saver': ^2.0.7
  '@types/fs-extra': ^11.0.4
  '@types/js-yaml': ^4.0.9
  '@types/katex': ^0.16.7
  '@types/markdown-it': ^14.1.2
  '@types/micromatch': ^4.0.9
  '@types/node': ^22.12.0
  '@types/plantuml-encoder': ^1.4.2
  '@types/prompts': ^2.4.9
  '@types/recordrtc': ^5.6.14
  '@types/resolve': ^1.20.6
  '@types/semver': ^7.5.8
  '@types/yargs': ^17.0.33
  '@typescript/ata': ^0.9.7
  '@unhead/vue': ^1.11.18
  '@unocss/extractor-mdc': ^65.4.3
  '@unocss/reset': ^65.4.3
  '@vitejs/plugin-vue': ^5.2.1
  '@vitejs/plugin-vue-jsx': ^4.1.1
  '@volar/language-server': ~2.4.11
  '@volar/vscode': ^2.4.11
  '@vue/compiler-sfc': ^3.5.13
  '@vueuse/core': ^12.5.0
  '@vueuse/math': ^12.5.0
  '@vueuse/motion': ^2.2.6
  bumpp: ^10.0.1
  chokidar: ^4.0.3
  cli-progress: ^3.12.0
  connect: ^3.7.0
  cross-env: ^7.0.3
  cypress: ^13.17.0
  debug: ^4.4.0
  drauu: ^0.4.2
  eslint: ^9.19.0
  eslint-plugin-format: ^1.0.1
  esno: ^4.8.0
  fast-deep-equal: ^3.1.3
  fast-glob: ^3.3.3
  file-saver: ^2.0.5
  floating-vue: ^5.2.2
  fs-extra: ^11.3.0
  fuse.js: ^7.0.0
  get-port-please: ^3.1.2
  global-directory: ^4.0.1
  gray-matter: ^4.0.3
  htmlparser2: ^10.0.0
  is-installed-globally: ^1.0.0
  jiti: ^2.4.2
  katex: ^0.16.21
  kolorist: ^1.8.0
  lint-staged: ^15.4.3
  local-pkg: ^1.0.0
  lz-string: ^1.5.0
  magic-string: ^0.30.17
  magic-string-stack: ^1.0.0
  markdown-it: ^14.1.0
  markdown-it-footnote: ^4.0.0
  markdown-it-mdc: ^0.2.5
  mermaid: ^11.4.1
  micromatch: ^4.0.8
  minimist: ^1.2.8
  mlly: ^1.7.4
  monaco-editor: 0.51.0
  nanotar: ^0.2.0
  nodemon: ^3.1.9
  open: ^10.1.0
  ovsx: ^0.10.1
  pdf-lib: ^1.17.1
  plantuml-encoder: ^1.4.0
  playwright-chromium: ^1.50.0
  postcss-nested: ^7.0.2
  pptxgenjs: ^3.12.0
  prettier: ^3.4.2
  prettier-plugin-slidev: ^1.0.5
  prompts: ^2.4.2
  public-ip: ^7.0.1
  reactive-vscode: ^0.2.10
  recordrtc: ^5.6.2
  resolve-from: ^5.0.0
  resolve-global: ^2.0.0
  rimraf: ^6.0.1
  semver: ^7.7.0
  shiki: ^2.1.0
  shiki-magic-move: ^1.0.0
  simple-git-hooks: ^2.11.1
  sirv: ^3.0.0
  source-map-js: ^1.2.1
  taze: ^18.3.0
  tinyexec: ^0.3.2
  tm-grammars: ^1.22.10
  ts-json-schema-generator: ^2.3.0
  tsup: ^8.3.6
  typeit: 8.1.0
  typescript: ^5.7.3
  unocss: ^65.4.3
  unplugin-icons: ^22.0.0
  unplugin-vue-components: ^28.0.0
  unplugin-vue-markdown: ^28.2.0
  untun: ^0.1.3
  uqr: ^0.1.2
  vite: ^6.0.11
  vite-plugin-inspect: ^10.1.0
  vite-plugin-remote-assets: ^0.6.0
  vite-plugin-static-copy: ^2.2.0
  vite-plugin-vue-server-ref: ^0.4.2
  vitefu: ^1.0.5
  vitepress: ^1.6.3
  vitest: ^3.0.4
  volar-service-prettier: ^0.0.62
  volar-service-yaml: ^0.0.62
  vue: ^3.5.13
  vue-router: ^4.5.0
  vue-tsc: ^2.2.0
  yaml: ^2.7.0
  yargs: ^17.7.2
  zx: ^8.3.1
