/**
 * Generated by tsnapi — public API snapshot of `@slidev/parser/core`
 */
// #region Interfaces
export interface SlidevParserOptions {
  noParseYAML?: boolean;
  preserveCR?: boolean;
}
// #endregion

// #region Functions
export declare function detectFeatures(_: string): SlidevDetectedFeatures;
export declare function extractImagesUsage(_: string, _: Record<string, any>): string[];
export declare function getDefaultConfig(): SlidevConfig;
export declare function parse(_: string, _: string, _?: SlidevPreparserExtension[], _?: SlidevParserOptions): Promise<SlidevMarkdown>;
export declare function parseSlide(_: string, _?: SlidevParserOptions): Omit<SourceSlideInfo, 'filepath' | 'index' | 'start' | 'contentStart' | 'end'>;
export declare function parseSync(_: string, _: string, _?: SlidevParserOptions): SlidevMarkdown;
export declare function prettify(_: SlidevMarkdown): SlidevMarkdown;
export declare function prettifySlide(_: SourceSlideInfo): SourceSlideInfo;
export declare function resolveConfig(_: any, _?: SlidevThemeMeta, _?: string, _?: boolean): SlidevConfig;
export declare function resolveFonts(_?: FontOptions): ResolvedFontOptions;
export declare function stringify(_: SlidevMarkdown): string;
export declare function stringifySlide(_: SourceSlideInfo, _?: number): string;
export declare function verifyConfig(_: SlidevConfig, _?: SlidevThemeMeta, _?: (_: string) => void): void;
// #endregion

// #region Other
export { isPathInsideRoots }
export { parseAspectRatio }
export { parseRangeString }
export { parseTimesplits }
export { parseTimeString }
export { TimesplitInput }
export { TimesplitOutput }
// #endregion