/**
 * Generated by tsnapi — public API snapshot of `@slidev/parser/fs`
 */
// #region Interfaces
export interface LoadRootsInfo {
  roots: string[];
  userRoot: string;
}
// #endregion

// #region Types
export type LoadedSlidevData = Omit<SlidevData, 'config' | 'themeMeta'>;
// #endregion

// #region Functions
export declare function injectPreparserExtensionLoader(_: PreparserExtensionLoader): void;
export declare function load(_: LoadRootsInfo, _: string, _?: Record<string, string> | ((_: string) => Promise<string>), _?: string): Promise<LoadedSlidevData>;
export declare function save(_: SlidevMarkdown): Promise<string>;
// #endregion

// #region Other
export { detectFeatures }
export { extractImagesUsage }
export { getDefaultConfig }
export { parse }
export { parseAspectRatio }
export { parseRangeString }
export { parseSlide }
export { parseSync }
export { parseTimesplits }
export { parseTimeString }
export { prettify }
export { prettifySlide }
export { resolveConfig }
export { resolveFonts }
export { SlidevParserOptions }
export { stringify }
export { stringifySlide }
export { TimesplitInput }
export { TimesplitOutput }
export { verifyConfig }
// #endregion