/**
 * Generated by tsnapi — public API snapshot of `@slidev/parser`
 */
// #region Other
export { detectFeatures }
export { extractImagesUsage }
export { getDefaultConfig }
export { parse }
export { parseAspectRatio }
export { parseRangeString }
export { parseSlide }
export { parseSync }
export { parseTimesplits }
export { parseTimeString }
export { prettify }
export { prettifySlide }
export { resolveConfig }
export { resolveFonts }
export { SlidevParserOptions }
export { stringify }
export { stringifySlide }
export { TimesplitInput }
export { TimesplitOutput }
export { verifyConfig }
// #endregion