/**
 * Generated by tsnapi — public API snapshot of `@slidev/parser`
 */
// #region Interfaces
export interface SlidevParserOptions {
  noParseYAML?: boolean;
  preserveCR?: boolean;
}
export interface TimesplitInput {
  no: number;
  timesplit: string;
  title?: string;
}
export interface TimesplitOutput {
  timestampStart: number;
  timestampEnd: number;
  noStart: number;
  noEnd: number;
  title?: string;
}
// #endregion

// #region Functions
export declare function detectFeatures(_: string): SlidevDetectedFeatures;
export declare function extractImagesUsage(_: string, _: Record<string, any>): string[];
export declare function getDefaultConfig(): SlidevConfig;
export declare function parse(_: string, _: string, _?: SlidevPreparserExtension[], _?: SlidevParserOptions): Promise<SlidevMarkdown>;
export declare function parseAspectRatio(_: string | number): number;
export declare function parseRangeString(_: number, _?: string): number[];
export declare function parseSlide(_: string, _?: SlidevParserOptions): Omit<SourceSlideInfo, 'filepath' | 'index' | 'start' | 'contentStart' | 'end'>;
export declare function parseSync(_: string, _: string, _?: SlidevParserOptions): SlidevMarkdown;
export declare function parseTimesplits(_: TimesplitInput[]): TimesplitOutput[];
export declare function parseTimeString(_: string | number): {
  seconds: number;
  relative: boolean;
};
export declare function prettify(_: SlidevMarkdown): SlidevMarkdown;
export declare function prettifySlide(_: SourceSlideInfo): SourceSlideInfo;
export declare function resolveConfig(_: any, _?: SlidevThemeMeta, _?: string, _?: boolean): SlidevConfig;
export declare function resolveFonts(_?: FontOptions): ResolvedFontOptions;
export declare function stringify(_: SlidevMarkdown): string;
export declare function stringifySlide(_: SourceSlideInfo, _?: number): string;
export declare function verifyConfig(_: SlidevConfig, _?: SlidevThemeMeta, _?: (_: string) => void): void;
// #endregion