/**
 * Generated by tsnapi — public API snapshot of `@slidev/parser/utils`
 */
// #region Other
export { isPathInsideRoots }
export { parseAspectRatio }
export { parseRangeString }
export { parseTimesplits }
export { parseTimeString }
export { TimesplitInput }
export { TimesplitOutput }
// #endregion