/**
 * Generated by tsnapi — public API snapshot of `@slidev/parser/utils`
 */
// #region Interfaces
export interface TimesplitInput {
  no: number;
  timesplit: string;
  title?: string;
}
export interface TimesplitOutput {
  timestampStart: number;
  timestampEnd: number;
  noStart: number;
  noEnd: number;
  title?: string;
}
// #endregion

// #region Functions
export declare function parseAspectRatio(_: string | number): number;
export declare function parseRangeString(_: number, _?: string): number[];
export declare function parseTimesplits(_: TimesplitInput[]): TimesplitOutput[];
export declare function parseTimeString(_: string | number): {
  seconds: number;
  relative: boolean;
};
// #endregion