import '@unocss/reset/tailwind.css'
import 'uno:preflights.css'
import 'uno:typography.css'
import 'uno:shortcuts.css'

import '@slidev/client/styles/vars.css'
import '@slidev/client/styles/index.css'
import '@slidev/client/styles/code.css'
import '@slidev/client/styles/katex.css'
import '@slidev/client/styles/transitions.css'
import 'katex/dist/katex.min.css'
import '@shikijs/vitepress-twoslash/style.css'
import '@slidev/client/styles/shiki-twoslash.css'
import 'shiki-magic-move/style.css'

import 'uno.css'
