/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Arrow: typeof import('./.vitepress/@slidev/client/builtin/Arrow.vue')['default']
    AutoFitText: typeof import('./.vitepress/@slidev/client/builtin/AutoFitText.vue')['default']
    CodeBlockWrapper: typeof import('./.vitepress/@slidev/client/builtin/CodeBlockWrapper.vue')['default']
    Demo: typeof import('./.vitepress/theme/components/Demo.vue')['default']
    DemoEditor: typeof import('./.vitepress/theme/components/DemoEditor.vue')['default']
    DemoSlide: typeof import('./.vitepress/theme/components/DemoSlide.vue')['default']
    Environment: typeof import('./.vitepress/theme/components/Environment.vue')['default']
    FeatureCard: typeof import('./.vitepress/theme/components/FeatureCard.vue')['default']
    FeatureCardLinks: typeof import('./.vitepress/theme/components/FeatureCardLinks.vue')['default']
    FeatureCardSince: typeof import('./.vitepress/theme/components/FeatureCardSince.vue')['default']
    LandingPage: typeof import('./.vitepress/theme/components/LandingPage.vue')['default']
    Link: typeof import('./.vitepress/@slidev/client/builtin/Link.vue')['default']
    Mermaid: typeof import('./.vitepress/@slidev/client/builtin/Mermaid.vue')['default']
    Monaco: typeof import('./.vitepress/@slidev/client/builtin/Monaco.vue')['default']
    PlantUml: typeof import('./.vitepress/@slidev/client/builtin/PlantUml.vue')['default']
    RenderWhen: typeof import('./.vitepress/@slidev/client/builtin/RenderWhen.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ShowCaseInfo: typeof import('./.vitepress/theme/components/ShowCaseInfo.vue')['default']
    ShowCases: typeof import('./.vitepress/theme/components/ShowCases.vue')['default']
    SlideCurrentNo: typeof import('./.vitepress/@slidev/client/builtin/SlideCurrentNo.vue')['default']
    SlidesTotal: typeof import('./.vitepress/@slidev/client/builtin/SlidesTotal.vue')['default']
    Starport: typeof import('vue-starport')['Starport']
    StarportCarrier: typeof import('vue-starport')['StarportCarrier']
    ThemeGallery: typeof import('./.vitepress/theme/components/ThemeGallery.vue')['default']
    ThemeInfo: typeof import('./.vitepress/theme/components/ThemeInfo.vue')['default']
    TheTweet: typeof import('./.vitepress/theme/components/TheTweet.vue')['default']
    Toc: typeof import('./.vitepress/@slidev/client/builtin/Toc.vue')['default']
    TocList: typeof import('./.vitepress/@slidev/client/builtin/TocList.vue')['default']
    Transform: typeof import('./.vitepress/@slidev/client/builtin/Transform.vue')['default']
    Tweet: typeof import('./.vitepress/@slidev/client/builtin/Tweet.vue')['default']
    Youtube: typeof import('./.vitepress/@slidev/client/builtin/Youtube.vue')['default']
  }
}
