# Continuous Releases provided by https://pkg.pr.new
name: CR (Continuous Releases)
on: [push, pull_request]

jobs:
  cr:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - name: Setup pnpm
        uses: pnpm/action-setup@0ebf47130e4866e96fce0953f49152a61190b271 # v6.0.9

      - uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          node-version: lts/*
          cache: pnpm

      - run: npm i -g @antfu/ni
      - run: nci

      - name: Build
        run: nr build

      - run: nlx pkg-pr-new publish './packages/create-app' './packages/client' './packages/create-theme' './packages/parser' './packages/slidev' './packages/types' --pnpm
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
