# Continuous Releases provided by https://pkg.pr.new
name: CR (Continuous Releases)
on: [push, pull_request]

jobs:
  cr:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Setup pnpm
        uses: pnpm/action-setup@0977fd99725f1db4007ccb2928dbb4e90d06cc86 # v6.0.10

      - uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          node-version: lts/*
          cache: pnpm

      - run: npm i -g @antfu/ni
      - run: nci

      - name: Build
        run: nr build

      - run: nlx pkg-pr-new publish './packages/create-app' './packages/client'
          './packages/create-theme' './packages/parser' './packages/slidev'
          './packages/types' --pnpm
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
