name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    permissions:
      id-token: write
      contents: write

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          fetch-depth: 0

      - uses: pnpm/action-setup@0ebf47130e4866e96fce0953f49152a61190b271 # v6.0.9

      - uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          node-version: lts/*
          registry-url: https://registry.npmjs.org/

      - run: npx changelogithub
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

      - run: npm i -g npm@latest
      - run: pnpm i
      - run: pnpm run ci:publish

      - name: Publish to VSCE & OVSX
        run: pnpm run publish
        working-directory: ./packages/vscode
        env:
          VSCE_TOKEN: ${{secrets.VSCE_PAT}}
          OVSX_TOKEN: ${{secrets.OVSX_PAT}}
