name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    permissions:
      id-token: write
      contents: write

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          fetch-depth: 0

      - uses: pnpm/action-setup@0977fd99725f1db4007ccb2928dbb4e90d06cc86 # v6.0.10

      - uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          node-version: lts/*
          registry-url: https://registry.npmjs.org/

      - run: npx changelogithub
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

      - run: npm i -g npm@latest
      - run: pnpm i
      - run: pnpm run ci:publish

      - name: Publish to VSCE & OVSX
        run: pnpm run publish
        working-directory: ./packages/vscode
        env:
          VSCE_TOKEN: ${{secrets.VSCE_PAT}}
          OVSX_TOKEN: ${{secrets.OVSX_PAT}}
